services:
  ansible-controller:
    #build:
    #  context: .
    #  dockerfile: Dockerfile_ansible_controller       
    container_name: ansible-controller
    image: iptcp/ansible-controller
    volumes:
      - ~/.ssh/ansible_docker:/home/ansible/.ssh/ansible_docker
    restart: on-failure
    hostname: ansible-controller
    environment:
      MAINTAINER: pbogdan
    ports:
      - "2220:22"
    networks:
      ansible:
        ipv4_address: 172.16.0.2
  ansible-target1:
    #build:
    #  context: .
    #  dockerfile: Dockerfile_target1_ubuntu
    container_name: ansible-target1
    image: iptcp/ansible-target1
    volumes:
      - ~/.ssh/ansible_docker.pub:/home/ansible/.ssh/authorized_keys
    restart: on-failure
    hostname: ansible-target1
    environment:
      MAINTAINER: pbogdan
    ports:
      - "2221:22"
    
    networks:
      ansible:
        ipv4_address: 172.16.0.3
  ansible-target2:
    #build:
    #  context: .
    #  dockerfile: Dockerfile_target2_centos
    container_name: ansible-target2
    image: iptcp/ansible-target2
    volumes:
      - ~/.ssh/ansible_docker.pub:/home/ansible/.ssh/authorized_keys
    restart: on-failure
    hostname: ansible-target2
    environment:
      MAINTAINER: pbogdan
    ports:
      - "2222:22"
    networks:
      ansible:
        ipv4_address: 172.16.0.4
        

networks:
    ansible:
        # use the bridge driver, but enable IPv6
        name: ansible_lab
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.0.0/24
                  gateway: 172.16.0.1
