apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      cni: cilium
  bgpInstances:
  - name: "bgp-cilium-instance"
    localASN: 65000
    peers:
    - name: "mikrotik-router"
      peerASN: 65001  # ✅ Must match your MikroTik's ASN
      peerAddress: 192.168.0.1
      peerConfigRef:
        name: cilium-peer
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
  namespace: kube-system
  labels:
    cni: cilium
spec:
  transport:
    localPort: 179
    peerPort: 179
  timers:
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          cni: "cilium"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements
  namespace: kube-system
  labels:
    cni: cilium
spec:
  advertisements:
    - advertisementType: "PodCIDR"