apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      cni: cilium
  bgpInstances:
  - name: "bgp-cilium-instance"
    localASN: 65000
    peers:
    - name: "peer-1"
      peerASN: 65000
      peerAddress: 192.168.0.84
      peerConfigRef:
        name: "cilium-peer"
    - name: "peer-2"
      peerASN: 65000
      peerAddress: 192.168.0.85
      peerConfigRef:
        name: "cilium-peer"
    - name: "peer-3"
      peerASN: 65000
      peerAddress: 192.168.0.86
      peerConfigRef:
        name: "cilium-peer"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
  namespace: kube-system
  labels:
    cni: cilium
spec:
  transport:
    localPort: 179
    peerPort: 179
  timers:
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          cni: "cilium"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements
  namespace: kube-system
  labels:
    cni: cilium
spec:
  advertisements:
    - advertisementType: "PodCIDR"
      #attributes:
      #  communities:
      #    standard: [ "65000:99" ]
      #  localPreference: 99
# ---
# apiVersion: cilium.io/v2alpha1
# kind: CiliumBGPNodeConfigOverride
# metadata:
#   name: bgp-override1
# spec:
#   bgpInstances:
#     - name: "bgp-instance"
#       routerID: "192.168.0.84"
#       localPort: 1790 # tried here to change to 179, but after that node disappeared from **BGP Peers** table
#       peers:
#         - name: "peer1"
#           localAddress: 192.168.0.85
#         - name: "peer2"
#           localAddress: 192.168.0.86
