version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      #interval: "weekly"
      #day: saturday
      interval: "daily"
    open-pull-requests-limit: 3
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
      time: "23:00"
      timezone: "Europe/Kyiv"
    open-pull-requests-limit: 3
  - package-ecosystem: "docker"
    directory: "/labs"
    schedule:
      interval: "weekly"
