---
- name: install Docker
  hosts: wireguard
  collections:
    - community.docker:3.1.0
  become: true
  vars:
    #docker_repo: https://download.docker.com/linux/centos/docker-ce.repo
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install or update needed software
      package: 
        name:
          - docker
        state: present
        update_cache: yes
      when: ansible_distribution == "Amazon"
    #- name: Install collection community.network
    #  collections:
    #    - community.docker:3.1.0
    - name: Install docker-compose package
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
        owner: ec2-user
        group: ec2-user
    - name: Adding user to run docker commands without sudo
      user:
        name: "{{ item }}"
        append: yes
        groups: docker
      become: true
      loop:
        - ec2-user
    - name: Create mount folder for wireguard
      file:
        path: /opt/wireguard
        state: directory
    - name: Deploy wireguard docker-compose stack
      docker_compose:
        project_name: wireguard
        project_src: .
        files:  
          - docker-compose.yml