---
- name: install Docker
  hosts: wireguard
  become: true
  vars:
    #docker_repo: https://download.docker.com/linux/centos/docker-ce.repo
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install or update needed software
      package: 
        name:
          - docker
          - docker-compose   
        state: latest
        update_cache: yes
      when: ansible_os_family == "Redhat"
