---
# Source: basic/templates/Combiner.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue
    lab: fish
  name: blue-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: blue
  sessionAffinity: None
  type: ClusterIP
---
# Source: basic/templates/Combiner.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: green
    lab: fish
  name: green-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: green
  sessionAffinity: None
  type: ClusterIP
---
# Source: basic/templates/Combiner.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-books-db
    lab: fish
  name: books-db
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: books-db
  sessionAffinity: None
  type: ClusterIP
---
# Source: basic/templates/Combiner.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    lab: fish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      
      name: api-gateway
      labels:
        app: api-gateway
    spec:
      containers:
        - image: iptcp/haystack
          name: haystack
          imagePullPolicy: IfNotPresent
          env:
            - name: PROFILE
              value: Traffic
            - name: LINK_CONFIG
              value: |-
                {
                    "Traffic": {
                        "Frequency": 250,
                        "TargetPool": [
                            {
                              "Url": "http://traffic-split-service.default/users"
                            },
                            {
                              "Url": "http://traffic-split-service.default/cards"
                            },
                            {
                              "Url": "http://traffic-split-service.default/checkout"
                            },
                            {
                              "Url": "http://traffic-split-service.default/books"
                            }
                        ]
                    }
                }
---
# Source: basic/templates/Combiner.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  labels:
    app: blue
    lab: fish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      
      name: blue
      labels:
        app: blue
    spec:
      containers:
        - image: iptcp/haystack
          name: haystack
          imagePullPolicy: IfNotPresent
          env:
            - name: PROFILE
              value: Middle
            - name: LINK_CONFIG
              value: |-
                {
                    "Passthrough": {
                        "Port": "8080",
                        "Endpoints": [
                            {
                                "Path": "/users",
                                "Targets": [
                                    {
                                        "Url": "http://books-db.default/users"
                                    }
                                   ],
                                "Latency": 125,
                                "FaultPercentage": 0
                            },
                            {
                                "Path": "/cards",
                                "Targets": [
                                    {
                                        "Url": "http://books-db.default/cards"
                                    }
                                   ],
                                "Latency": 30,
                                "FaultPercentage": 0
                            },
                            {
                                "Path": "/checkouts",
                                "Targets": [
                                    {
                                        "Url": "http://books-db.default/checkouts"
                                    }
                                   ],
                                "Latency": 300,
                                "FaultPercentage": 0
                            },
                            {
                                "Path": "/books",
                                "Targets": [
                                    {
                                        "Url": "http://books-db.default/books"
                                    }
                                   ],
                                "Latency": 3,
                                "FaultPercentage": 0
                            }
                        ]
                    }
                }
---
# Source: basic/templates/Combiner.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
  labels:
    app: green
    lab: fish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      
      name: green
      labels:
        app: green
    spec:
      containers:
        - image: iptcp/haystack
          name: haystack
          imagePullPolicy: IfNotPresent
          env:
            - name: PROFILE
              value: Middle
            - name: LINK_CONFIG
              value: |-
                {
                    "Passthrough": {
                        "Port": "8080",
                        "Endpoints": [
                            {
                                "Path": "/users",
                                "Targets": [
                                    {
                                        "Url": "http://books-db.default/users"
                                    }
                                   ],
                                "Latency": 50,
                                "FaultPercentage": 0
                            },
                            {
                                "Path": "/cards",
                                "Targets": [
                                    {
                                        "Url": "http://books-db.default/cards"
                                    }
                                   ],
                                "Latency": 30,
                                "FaultPercentage": 0
                            },
                            {
                                "Path": "/checkouts",
                                "Targets": [
                                    {
                                        "Url": "http://books-db.default/checkouts"
                                    }
                                   ],
                                "Latency": 300,
                                "FaultPercentage": 0
                            },
                            {
                                "Path": "/books",
                                "Targets": [
                                    {
                                        "Url": "http://books-db.default/books"
                                    }
                                   ],
                                "Latency": 3,
                                "FaultPercentage": 0
                            }
                        ]
                    }
                }
---
# Source: basic/templates/Combiner.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-db
  labels:
    app: books-db
    lab: fish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books-db
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      
      name: books-db
      labels:
        app: books-db
    spec:
      containers:
        - image: iptcp/haystack
          name: haystack
          imagePullPolicy: IfNotPresent
          env:
            - name: PROFILE
              value: Backend
            - name: LINK_CONFIG
              value: |-
                 {
                     "Responses": {
                         "Port": "8081",
                         "Endpoints": [
                             {
                                 "Path": "/users",
                                 "Latency": 10,
                                 "FaultPercentage": 0,
                                 "Contents": "Sample Backend Response books-db"
                             },
                             {
                                 "Path": "/cards",
                                 "Latency": 10,
                                 "FaultPercentage": 0,
                                 "Contents": "Sample Backend Response books-db"
                             },
                             {
                                 "Path": "/checkouts",
                                 "Latency": 10,
                                 "FaultPercentage": 0,
                                 "Contents": "Sample Backend Response books-db"
                             },
                             {
                                 "Path": "/books",
                                 "Latency": 10,
                                 "FaultPercentage": 0,
                                 "Contents": "Sample Backend Response books-db"
                             }
                         ]
                     }
                 }
---
# Source: basic/templates/Combiner.yaml
# This file contains the looping logic to generate the 
# Deployments, Services, ServiceProfiles, and TrafficSplits 
# that form the scalable application.
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: traffic-split-service
  name: traffic-split-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: blue-or-green
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: bg-traffic-split
  namespace: default
spec:
  service: traffic-split-service
  backends:
  - service: blue-service
    weight: 100
  - service: green-service
    weight: 0
