apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: blue-green-example
  namespace: default
spec:
  service: application-service
  # Second step has blue configured to take 95% traffic and green 5%
  backends:
  - service: blue-service 
    weight: 95
  - service: green-service
    weight: 5
