apiVersion: v1
kind: Service
metadata:
  # This will become the DNS name
  name: haystack-service
spec:
  selector:
    app: haystack 
  # This is how you expose ports
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
