apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: error-split
  namespace: booksapp
spec:
  service: books
  backends:
  - service: books
    weight: 90
  - service: error-injector
    weight: 10
