---
name: terraform-lint

on: [push, pull_request]

defaults:
 run:
   working-directory: ./labs

jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Terraform fmt
        run: |
          terraform fmt -recursive
      - name: Lint Terraform
        uses: actionshub/terraform-lint@main