name: Wireguard_provision
on:
  #push:
  #  branches:
  #    - main
  #    - master
  pull_request:
    branches:
      - main
      - master
  #To be able to run it manually    
  workflow_dispatch:

env:
  AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}


#defaults:
# run:
#   shell: bash
#   working-directory: ./labs/aws/vpn/wireguard  

jobs:
  dependabot:
    name: Dependabot auto PR
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
       pull-requests: write
       contents: write
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.3
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{contains(steps.metadata.outputs.dependency-names, 'my-dependency') && steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  wireguard:
    name: Wireguard infra provisioning
    runs-on: ubuntu-22.04
    
    defaults:
      run:
        working-directory: ./labs/aws/vpn/wireguard
    permissions:
      packages: write
      contents: read
      id-token: write
      #
    steps:
      
      - name: Check out code
        uses: actions/checkout@v3
          

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
          terraform_wrapper: false #Fixing jq output issue
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Initialize Terraform
        run: |
          terraform init -input=false
      - name: Terraform Validate
        run: |
          terraform validate
      - name: Terraform plan
        run: |
          terraform plan -var="AWS_SSH_KEY=${{ secrets.TF_VAR_AWS_SSH_KEY }}"
      - name: Terraform apply
        run: |
          terraform apply -auto-approve -input=false -var="AWS_SSH_KEY=${{ secrets.TF_VAR_AWS_SSH_KEY }}"
      #- name: Install jq
      #  run: jq --version
      # terraform output -json |jq --raw-output '.[].value'
      # echo "IP=$(terraform output -raw bastion_public_ip)" >> $GITHUB_ENV
      - name: IP output
        #id: ip_output
        id: ip_output
        run: |
          echo "::set-output name=ip_output::$(terraform output -raw bastion_public_ip)"
    outputs:
      #ip_output: ${{ steps.ip_output.outputs.IP }}
      ip_output: ${{ steps.ip_output.outputs.ip_output }}
          
          
  ansible_lint:
    name: Provisioning ansible infra part
    needs: wireguard
    runs-on: ubuntu-22.04
    #defaults:
    #  run:
    #    working-directory: ./labs/aws/vpn/wireguard/ansible
    steps:
      - name: Lint Ansible Playbook
        #uses: ansible/ansible-lint-action@main
        uses: ansible-community/ansible-lint-action@v6.3.0
        with:
          targets: "./labs/aws/vpn/wireguard/ansible"

  run_playbook:
    name: Run ansible playbok
    needs: [wireguard]
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./labs/aws/vpn/wireguard/ansible
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: Install Ansible deps
        run: |
          pip3 install --upgrade pip
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
          
      #- name: Check if we can use IP var
      #  run: |
      #    echo ${{needs.wireguard.outputs.ip_output}}
      #    ls -al
      
      #- name: Verifying ansible inventory invoking
      #  run: |
      #    echo ${{ secrets.ANSIBLE_INVENTORY }}
      - name: Deploy Wireguard automation
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          directory: ./labs/aws/vpn/wireguard/ansible
          key: ${{secrets.LAB_SSH_PRIV}}
          inventory: |
           [wireguard]
           ${{needs.wireguard.outputs.ip_output}} ansible_ssh_host=${{needs.wireguard.outputs.ip_output}} ansible_ssh_port=22 ansible_connection=ssh ansible_ssh_user=ec2-user ansible_become_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no'
          known_hosts: .known_hosts
          options: |
            --limit wireguard
            --verbose
        
        #run: |
        #  ls -al
  
  # deployAnsible:
  #   needs: ansible_lint
  #   runs-on: ubuntu-22.04
  #   #permissions:
  #     #packages: write
  #   #  contents: read
  #   #  id-token: write
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: ./.github/actions/ansible
  #   #- uses: ./github/actions/ansible
  #     with: 
  #       playbook: playbook.yml
  #       #playbook: ./.github/actions/ansible/playbook.yml
  #       inventory: localhost
        
