name: Wireguard_destroy
on:
  #push:
  #  branches:
  #    - master
  #    - main
  pull_request_target:
    branches:
      - master
      - main
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '0 0 * * *'
  #To be able to run it manually    
  workflow_dispatch:

env:
  AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
  AWS_SSH_KEY_PRIVATE: ${{ secrets.TF_VAR_AWS_SSH_KEY_PRIVATE }}

defaults:
 run:
   shell: bash
   working-directory: ./labs/aws/vpn/wireguard  

jobs:
  wireguard:
    name: Wireguard destroy infra
    runs-on: ubuntu-22.04
    if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'p-bogdan' }}
    permissions:
      #Expanding perms for dependabot
      contents: write
      pull-requests: write
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Initialize Terraform
        run: |
          terraform init -input=false

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve -var="AWS_SSH_KEY=${{ secrets.TF_VAR_AWS_SSH_KEY }}" -var="AWS_SSH_KEY_PRIVATE=${{ secrets.TF_VAR_AWS_SSH_KEY_PRIVATE }}"
