name: Wireguard_destroy
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  #To be able to run it manually    
  workflow_dispatch:

defaults:
 run:
   shell: bash
   working-directory: ./labs/aws/vpn/wireguard  

jobs:
  wireguard:
    name: Wireguard destroy infra
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Initialize Terraform
        run: |
          terraform init -input=false

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve
